# Generated by Django 5.1 on 2024-08-13 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_rename_acoounts_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantedtree',
            name='tree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trees.tree'),
            preserve_default=False,
        ),
    ]
