# Generated by Django 5.1 on 2024-08-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_plantedtree_tree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='users',
        ),
    ]
