# Generated by Django 5.1 on 2024-08-13 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0004_remove_accounts_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantedtree',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planted_tree_account', to='trees.accounts'),
        ),
        migrations.AlterField(
            model_name='plantedtree',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plated_tree_tree', to='trees.tree'),
        ),
    ]
