# Generated by Django 5.1 on 2024-08-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0009_accounts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='user',
        ),
    ]
